---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scala-times1-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scala-times1
        component: web
        layer: application
      name: scala-times1-web
    spec:
      containers:
      - name: scala-times1-web
        envFrom:
        - configMapRef:
            name: scala-times1-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/scala-times1:production
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scala-times1
    component: web
    layer: application
  name: scala-times1-web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: scala-times1
    component: web
    layer: application
  type: ClusterIP
